### ISSUE TITLE
Slow page loading

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#100]
We are experiencing really slow page loading. I've raised it with Clook but they haven't been able to resolve anything, though indicated there was a server issue which might be the cause. Are you able to cast any light on this?
Clook reply:
_Is there a particular action on the site that is performing badly for you currently, or, what error do you see when this doesn't load here? I can't reproduce an issue on the site in question at the moment however, there is an open issue on this server relating to performance currently being investigated by our sysadmins so it is possible that it's related to this, if I can determine this I can add this to the known info there._

**Comment by johnvanbreda** [comment]
@davidnicholls125 it took several minutes to get the NatureSpot homepage to load from a browser that's logged in, though it does work OK for logged out users (as that's LS Cache). 

Looking on the warehouse, we have a log of all web service requests and I can see over the last hour or so, there doesn't seem to be anything abnormal. The vast majority of requests are sub-1 second, there are just a few that take a few seconds, but nothing that would explain this. So the problem is more likely to be on Drupal or the server side. Also iRecord seems fine which confirms it is unlikely to be a warehouse problem.

Logging into CPanel works, but seems very slow, so I think there is a performance issue on the server. I managed to look at the resource usage section and it looks fine so I don't think NatureSpot itself is using abnormal CPU cycles.

**Comment by davidnicholls125** [comment]
OK thanks. I'll push Clook again as it does seem to be their server.

**Comment by davidnicholls125** [comment]
Clook are still working on it but no change so far....
