### ISSUE TITLE
Project tagging - urgent

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#107]
We are supporting Leicester University's bioblitz which takes place on Monday and want this listed as a project. I've set it up as shown below but it isn't listed on the Submit Records form - is this just a caching delay? Are all new projects automatically added to iRecord activities for the app to be used to link to this project? If not, could this be added urgently as it needs to be in place for Monday. Thanks!

![image](https://user-images.githubusercontent.com/80914584/170678816-080c4755-a8d0-49d5-a80a-439373eb0a0f.png)

**Comment by johnvanbreda** [comment]
To get the activity to appear on the recording form, there is a caching delay or you can load from the following URL to force the cache to update: https://www.naturespot.org.uk/content/submit-records?refreshcache.

I'll look into setting the app up now.

**Comment by johnvanbreda** [comment]
I've set the app up now. For future reference, to do this requires 2 things - firstly, a matching activity on iRecord with "NatureSpot Leicestershire & Rutland - " prefixed to the title and a warning in the description that the records are going to NatureSpot. You must also add iRecord app data entry to the "Group pages" section, plus a summary or whatever other reporting page you want on iRecord.

Then I need to alter the script that runs on the warehouse to include the new activity IDs in the transfer. If this was going to be a frequent event I'd suggest altering the script so that it picks up the activity names dynamically.

**Comment by davidnicholls125** [comment]
Thanks. At present it's not a frequent occurrence to add new projects but in time it may become more used.
