### ISSUE TITLE
non VC55 records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#113]
We have had another flush of records submitted from outside VC55 and the question has been asked again as to whether we can stop these getting mixed up in the NS database. I remember asking a few years ago and there wasn't an easy solution but maybe things have changed?
Is it possible to prevent these records from being submitted in the first place by recognising a grid ref outside VC55? If so maybe a pop up could advise on using iRecord instead.

**Comment by johnvanbreda** [comment]
There is no quick solution, but a possible approach would be to switch from using WMS (Geoserver) to load the boundary of Leicestershire on the map, to using the Indicia built in "Location boundary to draw" option. This means that, rather than the map showing the boundary as an image file loaded from Geoserver, it will actually have the boundary as a polygon drawn on the map which it can do calculations against. Then I can add a "Warn if outside location boundary" option to the code. In total, about 2-3 hours work I think.

**Comment by davidnicholls125** [comment]
Thanks. I think it is worth going ahead with this. Can we stop submission if outside the boundary rather than just give a warning?

**Comment by johnvanbreda** [comment]
Yes, I think that's going to be possible, will do this.

**Comment by johnvanbreda** [comment]
This is now done.
