### ISSUE TITLE
Parish/Wild Place species lists

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#124]
One of our regulars is promoting recording in her village of Houghton on the Hill and has questioned why the 'last seen' date on the parish page species list seems to be outdated. Some of her bird records, example below, were accepted two days ago but are not reflected in the species list tab. I wouldn't have thought it is a caching issue after two days?
Whilst looking at this, could you make a couple of changes to the Parish/Wild Place pages please:
1. add the recorder's name alongside the 'last seen' date on the species list tab (and download)
2. add a status symbol to the latest record list on the main page to indicate which records have not yet been verified
![image](https://user-images.githubusercontent.com/80914584/206013095-b238ca90-6d22-4419-8233-12bc26b90f6c.png)

**Comment by johnvanbreda** [comment]
1. Adding the recorder name to the species list would actually require a second report to fetch the data, with the results spliced into the existing report, so is complex and has a performance hit. That's because a query can use a function like 'max' to get the most recent date, but it can't then fetch a different field from the row containing the maximum date (at least not in a single hit). So, it's possible, but would be worth confirming that it's worthwhile before proceeding.
2. I've added the record status icons to the records list.

It's possible that the update delay is just caching, since there is a random element to the decision when to refetch a new copy of the cached data, in order to make sure that multiple reports don't 'line up' and all refresh on the same page hit. Next time you see a similar issue please can you clear the cache at https://www.naturespot.org.uk/admin/config/iform/cache then reload the page - that will confirm if the Indicia cache is the reason. There is also the LS Cache, but that will only affect you if not logged in.

**Comment by davidnicholls125** [comment]
OK let's leave off the recorder for now, thanks.
I've cleared the Indicia cache as suggested but it hasn't updated the species list dates. I'm looking at the Houghton on the Hill parish page - as an example there is an accepted Collared Dove record which was accepted on the 12/12/22 but on the species list it shows the latest seen date as 7/08/22. It was verified a week ago.....

**Comment by johnvanbreda** [comment]
Thanks - fixed. It wasn't caching, but the parish page was using an old version of the species report (different to the wild places which use Elasticsearch). I've updated it to the new version and it works OK now.

**Comment by davidnicholls125** [comment]
Thanks.
