### ISSUE TITLE
Cynipidae - breadcrumb menu

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#130]
Species pages for cynipid wasps aren't displaying the correct breadcrumb menu. I've checked the parent in relations and it is set to Bees, Wasps, Ants the same as other families. Any ideas?
Another issue with Cynipae:  the displayed images for Cynipid wasps are not the same if you view on the main Bees, Wasps, Ants gallery compared to jumping to Cynipidae on the family submenu – the submenu image is that selected for the galls gallery and not that put into the gallery section of Organise Images. eg Neurotus saliens. The family submenu should display the same images shouldn't it?
On main menu - page 6:
![Neurotus gallery image page 6](https://user-images.githubusercontent.com/80914584/209562505-6cc75ff9-e7ad-4123-87a9-776844e17f17.jpg)
On Cynipae submenu:
![Neurotus gallery image family submenu](https://user-images.githubusercontent.com/80914584/209562543-e9d3c3fe-1272-4567-8293-aef1c5c704b4.jpg)

**Comment by johnvanbreda** [comment]
The first issue was that the breadcrumb gets built from the menu taxonomy, but skips any taxonomy with caterpillar or gall in the term so that this part of the menu doesn't affect the breadcrumb. But, because the main taxon contained Cynipidae - Gall Wasps, it also got blocked. I've changed it to only exclude taxonomy for galls if Gall is the first word in the term which works OK I think.

Second issue still needs me to look into it.

**Comment by johnvanbreda** [comment]
The second problem was exactly the same issue, though in a different area of code. The Cynipid menu item name was triggering the gall filter. I've fixed that as well.
