### ISSUE TITLE
Associated species page

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#134]
We would like to add a new feature linked to relevant species pages - a page (or tab?) displaying the species associated with that parent species. Could we add a 2 new admin fields to each species page where we can select, if relevant, the parent taxon and add a few words describing the association? Then create a new page/tab, linked to the parent page, that displays both the gallery image for the associated species plus the text entry. Where there is a populated 'associated species' page then this should be made available on the parent species page, otherwise nothing needs to be shown.
If this makes sense (!) could you provide a time estimate so we can raise the funds? 
If there is more than one parent species, could this be accomodated? If this would be much more complex then we could just stick to the main association.

**Comment by johnvanbreda** [comment]
I'm not 100% sure I understand the use of the term "parent" in this requirement, is that just the species that the association is to be shown for?

Having additional fields on a species account is a bit fiddly, because each item needs to store the linked taxon's page, plus the association text, so it's not just a simple single value. Although I'm sure this is possible, another idea might be to add a new content type called "species association". When you add one of these, there are fields for selecting the "association from" species and the "association to" species. Plus a text box for info to show on the "from species" and another text box for info to show on the "to species". Then, the new assocations tab on the species account can list all the "associated to" species where the "associated from" is the species you are looking at, plus all the "associated from" species where the "associated to" species is the species you are looking at. So a single species association content item can appear on both of the associated species pages, but with different text if required. We could make it so that if the text is blank, then the assocation is not shown for the species the text was for.

As an example: a spangle gall is associated with oak. So, you create a "species association" and select Spangle Gall Wasp as the from species, and Pedunculate Oak as the to species. You enter text in the "text to show for from species" box but leave the "text to show for to species" box blank. This means that Pedunculate Oak, with a picture and text, will appear on the Spangle Gall Wasp page but nothing will appear on the Pedunculate Oak page as you left the text box blank.

Having a separate content type for the species association means that any number of species can be associated with any number of other species, so any ecological network can be described. It also means that you can add extra fields, like a drop down list of association types (parasite, host/prey, symbiotic etc).

I think this needs about 1.5 days since the view for the species associations tab could be fiddly to get right. However there is a chance that it will turn out to be easier than expected so it might not need quite so much time.

**Comment by davidnicholls125** [comment]
Thanks John, I think what you have proposed should work. Parent is simply meant to refer to the species that has the association. I wasn't thinking of it being a two-way relationship, even though it obviously is! Using your example of spangle gall, on the species page for Quercus robur it sounds like there would be a tab labelled 'associated species' (or something similar). On this tab I had envisaged not just a list but images too, ie a single image of Spangle Gall (gallery image?), a species name linked to the species page for Spangle Gall, and then some brief text. The text and species name I think are covered by your suggestion so can we include an image?
On the Spangle Gall species page, it would work in the same way but this time obviously with Quercus robur displayed.
Let me know if I've got this right and if the image inclusion works OK then we will look for the funding.

**Comment by johnvanbreda** [comment]
Yes, you've got that right. There are a couple of options, neither of which significantly affect the estimate:
1. Either use the same brief text to explain the association when viewed from either species account, or you can have a separate bit of text for when viewing the association from the first species vs the second species. So, you could explain the association from the viewpoint of the species being viewed and could leave it blank in order to hide the association for one species but not the other (you might not want hundreds of associations to appear on the Q. robur page for example, even though you do want each associated species to reference Q. robur).
2. Either use the gallery image, or the association could have an image showing the interaction which is shown, e.g. in our example, the gall in the context of the leaf rather than a close up of the gall, or a view of the whole tree.

**Comment by davidnicholls125** [comment]
That's great then, thanks. We just need the funding now... We can work through your options when we get there.

**Comment by davidnicholls125** [comment]
Based on our last chat about this and applying some of the approach adopted for the guides, you said approx 1 day of work so please go ahead with this. To summarise my ideas on this:

- add an additional tab to the species pages = "Associated Species" - but only to be shown where some content has been created for this tab. 
- tab layout to be something like the wildlife guides, with intro text at the top then an image + text for each selected associated species. 
- not sure how species would be selected - would it work like the guides, ie with a new content type? Silimarly it would be helpful to have default text on the species page but with the option to replace this with custom text.
- species name to be a link to that species page

**Comment by johnvanbreda** [comment]
I’ve done a first draft. To try it out you need to do two things:
1)	Add a new content item using the new “Species association” content type and fill in as follows:
a.	Title - this is not used other than to help you find the association in the content list when editing, so any label explaining the association, e.g. “Spangle Gall to Oak”.
b.	Description - this is the description shown for the association in the list. You can also specify a default association note in the species account and leave this blank.
c.	Taxa - link to the species account you want to show the association for. The association will appear on this species’ account page.
d.	Associated taxon - link to the species account you want to show the association to. This species will appear in the list of associations.
e.	Image URL filename - paste in the image URL to use, as per the wildlife guides.
2)	On the species Edit tab, you can specify “Associations introduction” which will appear at the top of the list of associations for that species, plus “Association default details” which is the default note shown for an association to this species, unless you override it in the Description box on the association content.

Once you’ve set up a few I can take a look and check the styling is working OK. 

Also, although I had the idea of an association working in 2 directions (i.e. a single association could appear on both the Spangle Gall and the Pedunculate Oak page), this adds a little complexity so I thought best to set up single direction associations first - you can always set up 2 if you need it to show in both directions. If you try it out and feel that 2 directional associations would be of benefit let me know and I can set it up.

**Comment by davidnicholls125** [comment]
Thanks John. I've set up Eriophyes crataegi with an association to Hawthorn:
https://www.naturespot.org.uk/node/250795
I've been to edit on the Hawthorn species page and added an intro so the tab now appears - but not the gall.... I added text to the description on the associated species page rather than in the default field. What have I done wrong?

**Comment by davidnicholls125** [comment]
I've added another linked to Hawthorn - Phyllocoptes goniothorax. This time I've added text to the default field.

**Comment by johnvanbreda** [comment]
I think you are expecting the associations to work the other way to the way I've coded it. You have set the associations from the gall to the host plant, which means they appear on the gall page, not the plant page. Try swapping the taxa over and see if it does as you expect.

**Comment by davidnicholls125** [comment]
Oops! Yes that has worked, they are both on the Hawthorn page now. A few initial comments:

1. We need a space between the images
2. Not sure if you have done this but trim the image height as done on the guides - ideally centring the image (ie trim equal parts top and bottom).
3. Align the species names with the top of the image
4. Create a small space below the intro text before the first entry. Maybe a subtle format differential for the the intro text? (eg very pale box?)
5. Could you make the three tab titles a little bolder/larger?

**Comment by johnvanbreda** [comment]
How's that now? I standardised the tabs with the wild places ones which are also bigger than normal.

**Comment by davidnicholls125** [comment]
Good thanks. Could you change the title of the species tab to 'Species account'?
I think we need weightings in order to order the display. Also can you add links to the edit screens for both the associated species content and the species page - just as on the wildlife guides?

**Comment by davidnicholls125** [comment]
Could you look at:
https://www.naturespot.org.uk/species/common-knapweed#tab3
The entry is in triplicate..... yet there is only one association. Alan set this up and couldn't get the image to display. I've changed the image and it works OK, albeit x3! However some of the image names are very long and have dates with slashes (/) so wondered if this might be causing the problem?

**Comment by johnvanbreda** [comment]
The slashes are caused by the recent image organisation and are correct - the problem with triplicates was a quirk of the query that the Drupal view runs. I've fixed that. I've also changed the tab title, added a weight field, and added edit links to the association and associated taxon.

**Comment by davidnicholls125** [comment]
Thanks.
