### ISSUE TITLE
2022 record download problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#137]
Some of the 2022 downloaded records have the count field formatted as a date (a list is attached). I've tried downloading a fresh dataset but the problem remains. I've also tried opening one of these records in edit to see what was entered on the form, but I got the error page below. We are waiting to send out the data so would appreciate your help asap! Thanks.
![image](https://user-images.githubusercontent.com/80914584/213461544-9dd8b147-e7c3-4c7e-b5b0-69d15d2f64db.png)

**Comment by johnvanbreda** [comment]
I’m pretty sure this is Excel rather than a problem in the download, it’s interpreting a CSV value of 6-20 as 20th June for example. Rather than double clicking the CSV file to open it, try using File ... Open in Excel, then specifying that the file is delimited and uses commas as separators. Then on the wizard page that lets you set the formatting for each column, scroll over to find the Count column and set it to text format rather than general. It should then import OK.

Leaving open as there is a second issue with the edit page to look into.

**Comment by davidnicholls125** [comment]
When I extract the file from the zip it appears as an Excel.csv file. I've tried open with, choosing Excel but it then doesn't give me any options, it just opens as before....
![image](https://user-images.githubusercontent.com/80914584/213485709-d21784e4-2055-435d-82d7-cdfe78afcf41.png)

**Comment by johnvanbreda** [comment]
Try loading Excel first, then use the File menu in Excel to open it.

**Comment by davidnicholls125** [comment]
Thanks - that worked!
