### ISSUE TITLE
Various tweaks and questions

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#139]
We held a trustee meeting earlier to review issues arising in the record data from last year and also look at the galleries. A number of varied actions were agreed, though some need your advice to know if they are possible. If any of these are relatively straightforward to do then go ahead.
1. We would like to make the attribute field required for certain taxon groups (such as moths and caddisflies). Can this be done?
2. Some of the recorder comments are very long and often irrelevant. Can we instal a character limit of 50 for the overall comment and 200 for the record comment? Assuming this is OK, can there be a warning if the limit is exceeded?
3. We ask recorders to enter the site name either as a known site or to put the nearest village first. Is it possible to have a greyed out entry in the location box that reinforces this but is replaced by the text you enter? eg. _Bradgate Park or Ratby, playing field_
5. We want to introduce a grid ref limit of 8 figures (10m sq). Can this be done?
6. We want to remove the species weightings from certain taxon groups so they display alphabetically. Can you do this directly on the database if we tell you which groups, to avoid the tedious job of changing each manually?
7. When we redetermine a record, the image copies on Drupal don't change. Could they be linked so that they did?
8. Can we remove the pagination on the latest images recently added to the species pages please.
9. Can the pagination at the bottom of each gallery page be repeated at the top?

**Comment by johnvanbreda** [comment]
1. Yes, we'd create a separate custom attribute specifically for the groups where it is required (even if the list of terms is the same). 
2. A bit of custom code - script added to the page would check as you type. I'd suggest just adding a warning, rather than blocking the post, in case there is something really useful that needs to be said. 
3. Needs a small change to the code to allow this, but yes, that's possible. 
4. Yes. Just a small config change on the form.
6. You'd need to remove the weights from the taxonomy terms for the species. I don't have any quick method of doing this - I guess it would be possible to write custom code but I'm not sure it would be worth the effort.
7. Yes, I'm sure this is possible, but it would take a few hours to change and test the code.
8. Yes - should the limit be 8 images and the other pages are no longer available?
9. I can't find any quick way of doing this unfortunately. Probably possible with a custom script but would take a few hours at least.

Points 1 - 4 are all fairly quick tasks (about an hour each).

**Comment by davidnicholls125** [comment]
Thanks. Go ahead with 1-4 and 7. Yes 8 visible images seems fine.

**Comment by johnvanbreda** [comment]
Point 2 - please can you supply a message to display when the limits are exceeded (can be a different message for each comment type).
Point 4 - please can you confirm that the limit to be applied is that the maximum resolution accepted is 10m, so the only thing being prevented is a 1m precision grid ref?

**Comment by davidnicholls125** [comment]
Overall comment message: Please be as brief. You have exceeded the character limit of 50. Additional comments about individual records can be added on the species row.
Record comment message: Please be brief. You have exceeded the character limit of 200. 
Point 4 - yes, we just want to prevent 1m grid refs. 
Also, I've now got confirmation for you to go ahead with point 6 (assuming a few hours is less than a day).

**Comment by johnvanbreda** [comment]
Point 4 - done.

**Comment by johnvanbreda** [comment]
Point 2 - done.

**Comment by johnvanbreda** [comment]
Point 3 - done.

**Comment by davidnicholls125** [comment]
Point 1 - attribute field - could the asterix be put into the label rather than in the entry box as it distorts the row layout at present?
![image](https://user-images.githubusercontent.com/80914584/222914995-41eee591-316d-46fa-bdf9-6bff80fc2fcd.png)

**Comment by johnvanbreda** [comment]
Point 1 - done, position of asterisk now in top right corner of control. Can't put it in the label as it varies per row.

Point 7 - done.

Are any of the remaining points (5,6 & 8) required or can this be closed?

**Comment by davidnicholls125** [comment]
Thanks. Point 6 is still a desirable change so can you go ahead with this please?

**Comment by johnvanbreda** [comment]
For point 6 - I've added a report for redetermined images to the warehouse, but waiting for Jim to return in order to fix the mechanism for pulling the reports code onto the live warehouse. Once that it is done, the (for my own info) the plan is to add a Cron task to the NatureSpot module which uses this report to fetch a list of changes. It will then find the image link nodes for each and correct the linked taxon.

Question for you @davidnicholls125 - if an image was previously published for a taxon, then turns out that the record was wrong so the image is on the wrong page, should I unpublish the image?

**Comment by davidnicholls125** [comment]
Yes, best to unpublish it I think, otherwise when redetted to the correct species we could end up with with duplicate gallery images.

**Comment by johnvanbreda** [comment]
This is now done. It runs as a background task checking redeterminations as they come in, doing about 100 per hour, so will take a little while to complete the whole dataset. Images end up in the unused images section of the organiser (as Drupal images, not warehouse). You can see a couple of examples that have worked for Large Marsh Horsefly:
https://www.naturespot.org.uk/ns/image-organiser?species=21006
https://irecord.org.uk/record-details?occurrence_id=71776 

Also Water Chickweed:
https://www.naturespot.org.uk/ns/image-organiser?species=17411
https://irecord.org.uk/record-details?occurrence_id=103010
