### ISSUE TITLE
Gallery problem

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#140]
Some of the text entered into the description field of the taxon group page in the taxonomy is repeating in the families set up as the next tier. See Bugs where the group intro then repeats above Miridae. This may be linked to the creation of a new subsection we set up this morning: 'Shieldbugs and allies' where we moved the relevant families into this section. We haven't done the rest yet so will wait until this issue is resolved.
![image](https://user-images.githubusercontent.com/80914584/215488062-1d3b756f-7a82-41b0-a08c-c1562860b523.png)
Similarly, I added some new expandable text into the beetles group page and this then also displayed in each family section and also only showed one species in a section. I've removed this text for now and temporarily copied it into the page below.
https://www.naturespot.org.uk/beetles_intro

**Comment by johnvanbreda** [comment]
The first problem is because of the way the grouping works in a Drupal view. The report is configured to output the great-grandparent, grandparent and parent of each species photo and will output a new section header if the great-grandparent, grandparent or parent changes. For shield bugs, the parent is the family, the grandparent is Shieldbugs and allies and the great-grandparent is Bugs.  For Miridaem the parent is the family and the grandparent is Bugs. So the system detects that the grandparent has changed and therefore outputs it again. 

Changing this logic would be very difficult. If all of the Bugs had this extra level in the hierarchy it would work though.

I'll have a look at the collapse problem now.

**Comment by johnvanbreda** [comment]
The second problem was because the collapsible text plugin was not enabled for the basic HTML text format, only the full HTML format which the FAQs were using. I've enabled it now for basic HTML so it can be used in any text content with this selected as the format.

**Comment by davidnicholls125** [comment]
Thanks John but the collapsible text is still causing the same problem when I paste it into the Beetles top level description.
The bugs issue makes sense and we can easily fix this one by standardising the levels.

**Comment by johnvanbreda** [comment]
I've pasted in your example and it seems fine - is it working for you (Beetles page)?

**Comment by davidnicholls125** [comment]
On the beetle page I'm still seeing the problem where the collapsible heading is in each family. also every family is repeated with just one species displaying. Are you seeing something different?
![image](https://user-images.githubusercontent.com/80914584/216057005-42d48397-ae47-492f-9942-a833f67b1b67.png)

**Comment by johnvanbreda** [comment]
The collapse component creates a unique ID in the code on the page for each copy on the page. That means that the code which groups the report by heading sees a different ID for every beetle species, therefore repeats all the headings. I've found a setting that asks the view to output the groupings based on the unrendered code which seems to have worked, as it uses the text you see in the description box rather than the code it generates.
