### ISSUE TITLE
Latest images not loading + Submit Records form issue

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#146]
Latest Images page loading is sometimes taking ages. This morning 1+2 loaded quickly but page 3 took over a minute. Page 4 was OK. This has happened quite regularly and is usually later pages, though occasionally even page 1 barely loads.

I've also experienced on several occasions a problem with adding images to a record on the Submit Records form. It appears to be when a comment has been added before an image is added, but it doesn't seem to happen every time..... I've had to delete the species row and re-enter it.

**Comment by davidnicholls125** [comment]
Just logged on and clicked on Latest Images (logged in version). It hadn't loaded after 90 seconds at which point I gave up....

**Comment by davidnicholls125** [comment]
I tried again and left it loading until I got this error message.
![image](https://user-images.githubusercontent.com/80914584/222187285-96d29057-7612-444a-903a-8f2814938e9d.png)

**Comment by johnvanbreda** [comment]
I've deployed a new version of the report which simplifies the query used to count the records for the pager, which was taking ages. In addition there were some queries running for another project which were "deadlocked", causing the server to struggle. I've resolved this so hopefully performance is much better.

The "Drupal already installed" message is a red-herring caused by the report timout.

**Comment by davidnicholls125** [comment]
Thanks. Any thoughts on the Submit Records image loading issue?

**Comment by johnvanbreda** [comment]
I think that's a different issue, but I'm not very clear from your description what is actually happening. Would you be able to describe what is happening when you upload images in a different issue please?

**Comment by davidnicholls125** [comment]
I'll wait to see if/when it happens again and then add it.
