### ISSUE TITLE
Image manager

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#158]
Will class="img-responsive" still work with the two image managers? I used the IMCE manager to add an image but the image responsive tag didn't work... We use this a lot so need a solution. I've added back the old image loader for now so we can continue to use it temporarily.

**Comment by johnvanbreda** [comment]
Are you adding img-responsive using the Source view of the content editor and editing the HTML? As far as I can see the class attribute can be added using this method to images added via IMCE or the media library (for the latter you are adding the class attribute to the element called drupal-media, not the element called img). If you are doing this and the class attribute isn't appearing in the code it is possibly due to the chosen text format as filtered HTML, for example, is more restrictive in order to prevent misuse in the forum.

Another option - for the media library (new) method, I can add custom classes to the outputs depending on the style you choose when you add the item or click the media button. E.g. I could add img-responsive just for the thumbnail style, or for the panorama style, or for all styles. We could also add more styles (=view modes) so you could have 2 versions of thumbnail for example, one with and one without.

**Comment by davidnicholls125** [comment]
I've added a new news story and used the media library with full html and it works OK thanks. However - it is displaying the image file name and I can't find the config setting to switch this off! Can you help please?
On a different point, I set the default to present the 'original' but it still displays a tiny thumbnail. I've now changed it to 'media library' and the original now displays..... Are the various display options configurable, eg,. the size of the thumbnail, panorama, etc?

**Comment by johnvanbreda** [comment]
I think the news story you refer to is this one: https://www.naturespot.org.uk/node/249743? If so does that mean you managed to get rid of the file name.

Yes, the image styles are configurable and we can add more. You can crop, resize and so-forth, it's fairly flexible. It may be better to identify new ones than alter existing ones, for example panorama will have been designed with the parish and wildlife guide headers in mind so changing it would affect their layouts.

**Comment by davidnicholls125** [comment]
It is the correct news story but the file name is still showing on the home page entry:
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/e0c97067-6f1e-4a60-ab63-e06845a59c78)

**Comment by johnvanbreda** [comment]
I've realised that the default view mode for the inserted media tool is "media library" which is the view mode designed for use in the popup that allows you to pick a file to insert - hence it's not really a good choice for viewing media inside content. The media library view mode is fixed to include the file name to help you choose the file.

On the example news item, I think you had inserted using the media library tool, then edited the body summary (so the correct text would appear when viewed in the home page). Then when you tried to fix the image to remove the filename, by replacing the media library version of the image with one inserted using the old IMCE tool, you didn't update the summary version. That's why it still showed the file name on the home page (since it's the teaser view of the content, which shows the summary version of the body text).

I've now removed the media library view style from the options available when inserting using the media library button. I've also added a full width view style, which uses a new full width media style that scales the image to max 1120px wide which is the width when shown on a normal NS page. That is now the default when you insert using the media library button and it won't show the image file name. There are a couple of other view styles available for inserting thumbnails and panoramas but we can add others if required.
