### ISSUE TITLE
Twitter feed

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#166]
We have a feed on the home page linked to the NatureSpot twitter account. However, due to changes by twitter this is no longer working. Do you know if it is possible to resolve this by using a different embedding system? If not, I think we need to remove it from the home page (at least for the time being).

**Comment by johnvanbreda** [comment]
Hmm, seems like Twitter is upsetting more than just us - see https://twittercommunity.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782/32. As noted, even their own documentation is full of the "nothing to see here" message!

I've disabled it for now, in the hope that Twitter sort it at some point and we can re-enable it. I don't think that any other modules will work either since Twitter is fundamentally changed such that you cannot see tweets without a login - i.e. broken for a significant use case.

**Comment by johnvanbreda** [comment]
Closing as there has been no change at the Twitter end - but please re-open a new incident if you find out things are back as they were.
