### ISSUE TITLE
Home page amendments

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#172]
We would like to make a few amends to the home page following the demise of the twitter feed! I can probably do some of the tweaks myself but will need your help with a few items.
1. Remove the thin column so we just have 3 columns. I've disabled some of the features we've decided to ditch and moved the others into column 1, so it is empty now.
2. Align the top of the latest image with the news label (the log in label aligns but for logged in users this is hidden).
3. Can we format the 'more' links at the bottom of the events block and the 'latest chat' block? Currently they seem to get lost in the entries above. 
4. If we wanted to display two 'latest images' photos, is it possible for me to amend it as a trial and change back if preferred?
5. It is possible to have a 'more' link at the bottom of the news story block, giving a list of links to previous news stories no longer displayed, but is there a page to link to?
6. Latest chat - is this a view? I want to change the wording of the 'more' link but can't find the config.
7. Finally.... the home page is still too slow to load. Is there anything more we can do to speed this up?

**Comment by johnvanbreda** [comment]
1. Done
2. Done
3. I've added bold/underline - is that OK?
4. Done - it requires a tiny code change so let me know if you want it reset to 1.
5. Done - I had to add a page for the latest news.
6. No, it wasn't a view, but I've made it into one so we have more control. As it's a link to the forum (not to the views page) the more link is a custom footer, in the NS active forum topics view.
7. I've managed to work out that the LiteSpeed cache module wasn't working, probably due to a Drupal upgrade. I've corrected that which may reduce load on the server a bit. For future reference, the following needs to be in .htaccess:
```
<IfModule LiteSpeed>
CacheLookup on
</IfModule>
```

**Comment by davidnicholls125** [comment]
Thanks John. I can't find the active forums topic view - or at least can't see how to amend the custom footer in admin/structure/forums.
I don't think litespeed works on the home page for logged in users, it still seems to be as slow as usual. If this is the case, can we do anything more?
Thanks for trialling the second latest image but it doesn't work very well due to very similar images appearing together. Can we go back to one image please?
Can I change the order of the elements in the far right column? It isn't on the 'manage display' tab.

**Comment by johnvanbreda** [comment]
The view was called "NS active forum topics" - I added NS at the beginning as I think a future version of the forum will use a view called Active forum topics, to keep ours separate. It's here: https://www.naturespot.org.uk/admin/structure/views/view/ns_active_forum_topics. To change the text just click on the link in the footer section - you have to edit the raw HTML so only change the text between the > and the < symbols.

I've reverted to 1 latest image.

The far right column is managed by the overall blocks system, not the page display, as these blocks appear on multiple pages. The Display tab is only for layout of the centre section of the page that differs on every page. To manage the block order, go to Structure > Blocks. You can use the drag handles to change the order of the blocks in the Secondary section, then press Save blocks.

How long are you experiencing the home page taking when logged in? Experimenting just now, if I clear all the caches, it takes about 5-6s, but a full page rebuild is never likely to happen. If I load the page without doing that, I'm finding it takes 1 to 5 seconds. 

I've tweaked the way that views are cached on the home page, so they shouldn't get rebuilt every time a node is edited (as you can sometimes have lots of edits) - they now rebuild every hour or so. I'm not convinced this will make much difference though. I've also checked performance on the warehouse and I don't think Indicia performance is the problem here - our logs only show about half a second of delay caused by the warehouse when the caches are cleared before loading the home page.

One other thing suggested on the Drupal status report page is to enable something called APCu caching on the server:

> PHP APCU CACHING Not enabled
> PHP APCu caching can improve your site's performance considerably. It is highly recommended to have [APCu](https://www.php.net/manual/apcu.installation.php) installed on your server.

I think you'd need to ask Clook if this is an option?

**Comment by davidnicholls125** [comment]
Thanks John, I hadn't realised the forum element was a view so didn't look there. 
I've asked Clook about APCu and they don't use it. Apparently the used its predecessor APC but said they will look into it.
