### ISSUE TITLE
Forum module

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#173]
The forum module we are using seems a bit dated and is rather clunky. Do you know if there is an alternative?

**Comment by johnvanbreda** [comment]
There used to be a module called Advanced Forum but it was never ported to Drupal 8+. But, a bit of effort spent improving the theming might make it look more modern and there are likely to be customisations we can make if any specific functionality changes can be identified. Do you have any particular requirements?

**Comment by davidnicholls125** [comment]
Alan deals with much of our news, social media and forum posts so I asked for his ideas - response below:

Inevitably the forums will be compared to social media such as facebook and twitter.  In that regard the handling of images is particularly poor.  This matters because the primary purpose of the forums has become identification rather than text-based discussion. The lack of drag and drop image publishing makes them look antique and feel like something from the 90s.  It puts many posters off. This has been the standard for over a decade now.  In addition, the display of published images is poor - tiny thumbnails you have to click on which then drags you off to a dead screen (image only).  Full width image display needs to be that standard. 

Do you think it is possible to respond to some of these points?

**Comment by johnvanbreda** [comment]
Yes - I used the upgrade opportunity this morning to add a module allowing drag and drop of modules for forum posts. It's not quite as simple as Facebook in terms of the interface but should work well.  I've also resized the thumbnails so they are full width and added the Colorbox module so they pop-up within the page rather than loading a new page when clicked. Finally I set maximum image dimensions and upped the maximum file size so you can add a much larger file from a modern camera but it will get resized before sending to the server.

Please close if these changes are OK.
