### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#175]
We want to start sending out a regular newsletter, perhaps monthly but possibly quarterly. We did have a module many years ago but there are probably better options available now. Mime-mail appears to be the most popular. What would you advise?
We'd like to send it initially to all registered users but then give them the option to unsubscribe, is this possible? We will probably need a bit of help getting it set up initially. Thanks.

**Comment by johnvanbreda** [comment]
It's not an area I have great expertise in, but I would suggest looking into an option like MailChimp as well, because the latter sends the emails for you whereas the Drupal Mime Mail module sends the emails from Drupal. If sending lots of emails causes a red-flag regarding spam, then the NatureSpot website itself would be unaffected. That's not a recommendation for either, but something to bear in mind. I am sure that both would offer an unsubscribe feature.

**Comment by davidnicholls125** [comment]
OK thanks. I've used mailchimp previously for a tennis club newsletter so will look into this.
