### ISSUE TITLE
Missing records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#180]
No images or records are displaying on Agromyza abiens/myosotidis/lithosperma agg. though there are accepted records and the VC55 map shows the dots.

**Comment by johnvanbreda** [comment]
One problem I've noted is that there is another taxon with the same key: https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/473480

I'm not sure that fixing that will help. Are there other taxa which are not on UKSI, that have a "special" key allocated? If so, do the images show on their species pages?

**Comment by davidnicholls125** [comment]
There are lots with invented TVKs. I've checked the first two on the list and they are also missing records and images so it looks like a generic problem with these made up TVKs. I'm sure they did allow the records/images to display however so has something changed? I've listed a few examples below.

Acleris emargana -   effractana agg.
Agonopterix heracliana agg.
Agromyza abiens/myosotidis/lithosperma   agg.
Agromyza pseudoreptans/reptans agg.
Agyneta saxatilis
Caloptilia robustella - alchimiella agg.

**Comment by johnvanbreda** [comment]
I've fixed this now - the problem would have occurred some while ago when switching to Elasticsearch for fetching the records and images for performance reasons. since the code depended on a valid NBN Key that exists in UKSI. I've also added a message to explain why the NBN Atlas map doesn't work in these cases.
