### ISSUE TITLE
Tagging records that are accepted by the County Recorder 

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#2]
At the year end we send the relevant taxa record set to each County Recorder for them to check and approve. If requested by the CR we amend the verification status of these records. We want to tag the records thus accepted and show this to the recorder. We need to be able to filter records (record reference range + taxon group) and add a comment that these are 'CR accepted' - perhaps in a new field. 

A few taxon groups have more than one CR (eg bats and badgers within mammals) so we need a further selection option - perhaps a tick box (with the option to select all). 

We also want the recorder to be able to see which records have been accepted by the CR so perhaps add an asterix (or other symbol) to the verification icons?

**Comment by johnvanbreda** [comment]
There is an existing development, currently complete but not yet running on the live servers, where you can download records from a verification page, then verify them off-line by adding comments and filling in a status column. Then, they can be uploaded directly from the verification tool (Elasticsearch version) and the records will be updated.

Is tagging the records which are verified by the CR because you want to be able to separate them from verifications by National schemes? If so I think we will need to have flags and icons to say that a record has been accepted by county and/or national recorders. I think this is a broader issue that we ought to discuss with Martin Harvey at BRC to make sure we build something that is broadly useful.

Given the above, what is the need to separate out verifications by county recorders for mammals as opposed to for bats? Does the verifier name not do this? Would tagging record with the the verification filter title used for the verification serve this purpose (e.g. a filter title might be "John van Breda; Dorset; Butterflies" if I were the county butterfly recorder). Then you could see that it was verified by the bat, as opposed to the butterfly recorder.

**Comment by davidnicholls125** [comment]
The new development you describe sounds like it would do the job in the main.
The reason for wanting to do this is that the verification that we do is not valued as highly as that from a County Recorder (even though in reality we get 99%+ correct). The County Records Office uses a verification grade with CR and national verifier reviews being the highest grade. At the year end we send the NS datasets to CRs for them to check and those approved get upgraded by the Records Office. A couple of CRs have asked if we could let recorders know which of their records have been checked and approved by them. I was therefore wanting a relatively simple way in which we could add a tag to batches of records (mainly by taxon group) when the CR has approved the dataset we send them. Verifications by a national verifier would receive the same 'approved' tag as these are seen to be of equally high status. Does this make sense?

**Comment by johnvanbreda** [comment]
Yes, that makes sense. I think we should trial the new (untested but complete) code for downloading records from the verification tool, applying offline verification decisions, then uploading them. In fact as long as you know the record ID and format for the record status and comment, there is actually no need for a separate download. You would provide a spreadsheet that has 3 columns: ID, status and comment. The record ID is obvious, the status would be "Accepted" or "Accepted as correct" etc. Finally the comment could be "Verified by the County Recorder for Bats, *name of verifier*". That would notify the user that their record has been accepted by the County Recorder, what taxon group they are CR for, and their name. Also although this doesn't mean anything to Indicia (other than being just an additional verification event), in future if the system is enhanced to separate out verifications by different types/levels of expert, then all the information is to hand so we can automate any data changes to benefit from the enhancements.

Does that make sense? If so I will create a variant of the verification tool with upload enabled, probably a couple of hours work once I double check everything.
