### ISSUE TITLE
Gallery Image Weightings not working

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#211]
Where species have a ‘0’ weight, the Gallery Image Weightings don’t work. Examples are Eurydema oleracea and Picromerus bidens.  The selected gallery images now appear at the end of the Pentatomidae gallery, with image weight 1 first, then 2, then 3 – thus scrambling up the images.  
The gallery image weightings work fine where we have a species weighting other than zero.

**Comment by johnvanbreda** [comment]
I can't see what you mean here - the gallery views are always sorted by attributes of the species first, then the gallery image weight is only used to sort the images within the group for that species, so should not affect the overall position of the species in the family. Can you send me links to pages that illustrate what you mean please, as when I view the Pentatomidae gallery the image order is alphabetical which is correct (as the species weights are all 0).

**Comment by davidnicholls125** [comment]
I agree they look fine now so I'll close the issue and flag it if it seems to occur again.

**Comment by davidnicholls125** [comment]
Spoke too soon! Sue has pointed out that the problem remains. Look at the bugs gallery (image below) and you will see that adult and nymph images for each species are jumbled up. The order is fine on the individual species pages.
![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/1432e58f-53c6-45b3-a532-09e0d1e1c4d5)

**Comment by johnvanbreda** [comment]
These bugs had the weight set on their edit tabs to zero so there was nothing that sorted them separately. I've changed the view to sort by species scientific name in this instance.

**Comment by davidnicholls125** [comment]
I don't understand.... we have deliberately set weightings at zero on a number of galleries knowing that it then orders alphabetically. Why didn't that work in this case?

**Comment by johnvanbreda** [comment]
The view did have a fallback to sort alphabetically, but it was a lower priority than the "gallery image weight" given on the species edit tab, so this could have caused it to go out of order. I've made the alphabetical sort come before the gallery image weight so this will no longer happen. Please close if that makes sense.

**Comment by davidnicholls125** [comment]
I still don't understand why two images from the same species (therefore with the same weight and same A-Z spelling should be split up. Whether the gallery orders on weight or on A-Z they should surely still be grouped together? 
I think we want the order to be weight first then alphabetical within the same weight. I thought this was how it was working until the bug issue emerged. In other galleries it seems work that way.

**Comment by johnvanbreda** [comment]
It's because the gallery image weight, which should have been used to sort the gallery images only within a single species' images, was given too high a priority so it came above the alphabetical sort. The sort order was previously: species weight, then gallery image weight, then species name alphabetically. As the first Green Shieldbug and the first Spiked Shieldbug images had a gallery image weight set to 1, they both came before the next Green Shieildbug image which has it set to 2. So, the image ordering was only broken if the gallery image weights were used AND the species weights were left at zero, which is why it worked OK in many cases but not in this one. I've fixed the sort order now so that it is species weight, then species name alphabetically, then gallery image weight, so the species images are always grouped together now and gallery image weight only affects things within the set of images for that species.

**Comment by davidnicholls125** [comment]
I've just had the comment below from Sue..... please could you look into this. Thanks.

_I don’t know if this is connected with the tweak JvB just did to allow us to re-order the display of photos ion the galleries – but have just noted that the Miridae have scrambled up.  They all have a weighting of ‘0’ but are not in alphabetical order.  It looks as though they are now in the order of date set up, with the most recent new species at the end._

**Comment by johnvanbreda** [comment]
I've inspected the queries and realised that it was using the numeric ID of the taxonomy term, rather than the term itself, so it was unreliable. I've changed this and it should be OK now.
