### ISSUE TITLE
Missing taxonomy term

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#217]
The beetle family Curculionidae does not display on the species taxonomy browse page - https://www.naturespot.org.uk/species-taxonomy-top. It is listed in the relations drop down however and many species have this as their parent entry. The Curculionidae entry has 'Coleoptera- beetles' entered as its parent (within 'Insects'). There seems to be something different about this term which prevents it from showing on the browse page above. The only thing I can see that is different to any other term is an extra button at the bottom of the edit page which says 'Save and go to list'. This doesn't show on the other terms and brings up a blank page when clicked. As there are a lot of species entries under the Curculionidae family entry we don't want to lose these but we do need it to display so we can add further species entries. Can you work out what is happening?

**Comment by johnvanbreda** [comment]
I've created a view for searching terms as it can be hard to find them in the taxonomy - see https://www.naturespot.org.uk/term-search. If you search for Curculionidae then you will see that it is linked to some images directly - https://www.naturespot.org.uk/term-search?name=Curculionidae&vid=All, but the view that makes the species taxonomy page will only show a taxon term if it is either linked to a species page, or nothing at all. So it is filtering this family out because of the image links. 

Do you know why it is linked to these 2 images? Is it safe to delete them?

**Comment by davidnicholls125** [comment]
Odd! How do I view the images to check what they are? If I delete the image links will this correct the display problem? The problem arose when Sue was trying to set up a new species and I suspect she got muddled and perhaps created the image links in error. The images may need reallocating to the correct taxon....

**Comment by johnvanbreda** [comment]
Click on the title of the image in the view, then click Edit to see the contents of the File Name field (which may be the same as the title but not always). Add this value to https://warehouse1.indicia.org.uk/upload/, for example https://warehouse1.indicia.org.uk/upload/o_1hd45ge38igime4vurald1hgie.jpg.
