### ISSUE TITLE
missing record 'dot'

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#224]
Graham has reported that the record highlighted below (35393419) was verified a couple of days ago but hasn't generated a dot on the VC55 map. This seems to happen fairly regularly, do you know why?

![image](https://github.com/johnvanbreda/naturespot-d8/assets/80914584/3d2e3dfd-4ccf-4221-840e-cd00a218829d)

**Comment by johnvanbreda** [comment]
I've fixed this case. The record was input as Melanostoma scalare and was verified by Roger Morris who redetermined it as M. mellinum. In doing so, rather than pick from the NatureSpot list he ticked the option to search the full UKSI list and picked the redetermined name from there. This resulted in the keys not matching so the record won't appear on the map, as the filter assumes the species will be picked from the NatureSpot list.

We could switch to filtering by TVK which may avoid problems like this (though is unlikely to solve all problems) - about an hour's work.

**Comment by davidnicholls125** [comment]
Thanks John. I was aware it had been redetted on the UKSI but assumed this wouldn't be the cause as the TVK is the same. Please go ahead and set up the TVK to use from now on.

**Comment by johnvanbreda** [comment]
I've done that - the record had already appeared somehow, but it now loads using the TVK for the future.
