### ISSUE TITLE
Submit records / 403

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#244]
There are a few links to the Submit Records page around the site and these are viewable to non-logged in users. However if they click on the link they get a 403 error. Is it possible to redirect non-logged in users to the page below if they try to access submit records page?
https://www.naturespot.org.uk/register

**Comment by johnvanbreda** [comment]
I can change all attempts to access an unauthorised page so they go to the register page, but not just ones that are links to the Submit Records form (or at least, not without custom code). Shall I do that?

Also the page https://www.naturespot.org.uk/node/231862 which is shown when you access an unauthorised page has a title "403 error" which many users will not understand - a title like "Unauthorised" is a bit clearer? This page could also have a page alias "/unauthorised" rather than just a node number.

**Comment by davidnicholls125** [comment]
I've edited the 231862 page as suggested. Can you direct all attempts to view an unauthorised page to this? We will need to leave the Submit Records links for now I think.

**Comment by johnvanbreda** [comment]
That's done.
