### ISSUE TITLE
Submit Records form not loading

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#248]
When trying to bring up the Submit Records form it shows a 403 error. It also shows that I've been logged out. We've tried it in different browsers but with the same result.

**Comment by johnvanbreda** [comment]
I'm not seeing this problem now - either as admin, or masquerading as a normal user, in 2 different browsers. Are you still getting a 403 error?

Was the error basically a blank page with 403 in a large font (maybe a little bit of extra text)? If so that comes form the server rather than Drupal. However if you see anything similar again I'd recommend clearing the Drupal cache to see if that fixes it.

**Comment by davidnicholls125** [comment]
I was until an hour ago but it has cleared now..... The error page had the text we added about some pages not appearing unless you were logged in. My guess is that the problem was it logging you out when moving onto the page, though why I've no idea. We have experienced similar logging out problems before. If it happens again I'll try refreshing the drupal cache as suggested. Thanks.

**Comment by johnvanbreda** [comment]
One more thing to check then - before you follow the link AND after, the web address should be one that starts https (not http) and has www. before naturespot.org.uk. A while back there was a similar problem because a link was to a slightly different form of the address, so it had the effect of logging out. There is code to prevent this now though so it shouldn't be the cause, but worth checking.

**Comment by davidnicholls125** [comment]
OK thanks.
