### ISSUE TITLE
Deleting records

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#48]
We need to delete around 100 records that have incorrect details (they are also duplicates). I can't find a way to do this in bulk (with either the old or elasticsearch verification pages). Is this possible? Similar we frequently need to redet multiple records from one species name to another and again this is ideally done as a bulk record action. Why aren't these actions offered together with the verification options? Equally annoying, when you do delete a record you are taken to the thank you page and have to go through the whole search/filter process on the verification page all over again for each record. Can we return to the verification page after an edit? Thanks.

**Comment by johnvanbreda** [comment]
Several questions here. Firstly, bulk record operations like this have been considered but have never reached the top of my pile of things to develop for BRC, possibly because each case is often needing individual consideration (so best handled by a custom query) and also because on iRecord, the original recorder probably doesn't want to find their records have been bulk-deleted even if wrong. It's not considered the verifier's responsibility to tidy records, it's the recorders. 

For the edit link on the verification page it is deliberately a link rather than a button. That means you can right click and open it in a new tab, so the verification page doesn't lose it's current position.

If you send me the 100 record IDs to bulk delete I can do that for you.

**Comment by davidnicholls125** [comment]
Thanks John. I hadn't realised we could open the edit page in a separate window, that makes it easier!
We don't delete records just because they are incorrect. In this case they were third party records submitted without the original recorder's permission and misleadingly appearing as records of the person who uploaded them. We weren't aware of this but received a complaint so have had to delete them. They are all done now but thanks for the offer.
Having a bulk redet function would be very useful!
