### ISSUE TITLE
User name vs Recorder name (Rogue records)

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#50]
Just noticed that on the Ashby parish page, the latest records displaying are listed as mine but I haven't added them. They don't appear to be in the database when checking on the verification page and on Indicia. Also they are in pairs that look like duplicates. Any idea what is going on here?
![image](https://user-images.githubusercontent.com/80914584/125443027-dfa582fe-eeaf-469e-bae0-d49ef402a73f.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 the records were imported by you in 2018 for a recorder called STWA. The system is setup to use the Drupal username for recorder names so that's why it comes up with your name. They aren't duplicates though - the 2 bream records for example have different grid references.

They appear at the top because the sort is done using the start of the range of possible dates. In this case there is no start of the range of dates, so it counts as "null" which causes the database to put it at the top of the list. I could investigate changing how this works but it will need to be done carefully so as to not affect other parts of the system, so is not a simple task.

**Comment by davidnicholls125** [comment]
OK thanks.
It is confusing and misleading that I'm shown as the recorder just because I ran the import. Can the record display use recorder names rather than usernames?
So it sounds like these records will be permanently displayed as the 'latest' records, which we don't want. Could I change the date entry by editing the records to something that would work?

**Comment by johnvanbreda** [comment]
@davidnicholls125 yes, changing the date range would work. Is there a reason why you only know these records were "any time before the end of 1978" for example? If you knew they were e.g. in the 1970s we could set 1970 as the start. Let me know if you want me to apply any changes.

For the recorder name issue, I have a vague recollection that you specifically wanted usernames to appear, not the recorder's full name. However looking at the terms and conditions document it is pretty clear that the recorder's full name can be shown. It's the need to show usernames (which therefore means the logged in user who "owns" the record) rather than the recorder name that is causing the issue here.  Note that if we switch to the recorder name field, it is going to show surname, firstname format at least initially (though I know this format is under review and likely to change).

**Comment by davidnicholls125** [comment]
These were added as historic records for the Black to Green project that wanted as much data as possible, but the date wasn't provided. However 1970 to 1978 would be fine. I can't do this as a form edit so could you amend these? Thanks.
I'll check with the trustees to see if there are any issues with displaying recorder names rather than user names but it would seem sensible to me. The Explore page already uses recorder names.

**Comment by davidnicholls125** [comment]
The questions of whether to display user names or recorder names has led to considerable discussion and raised a number of questions about GDPR which we would appreciate your view on. We originally elected to display user names as we felt some people wouldn't want their real names published. However iRecord and the Explore page do use recorder names so we have a mixed picture currently. Whilst the terms permit us to display real names, some trustees are worried this might upset some recorders if we adopted this approach. I imagine some of these questions have been considered by CEH and iRecord.
1. How easy/difficult would it be to add an option to the My Account page that gave recorders an option of having their username instead of their real name displayed with images and records? (Possibly create a 'name display' field that is populated by the real name as the default but replaced with the user name if the recorder chooses this option)
2. Could this option be applied to the Explore page?
3. Can a recorder require all their record data to be deleted? This isn't totally clear in the terms, it just mentions their right to have their address and email details removed "Your full name will remain a key part of any record data that you have submitted but your postal address and email will be deleted should you request this." The terms say that the user retains ownership of the content they upload (eg records and images) but gives NatureSpot a licence to use this data. The key question is can this permission ever be revoked?

**Comment by johnvanbreda** [comment]
1. & 2. possibly, but it's not an easy task, primarily because there are lots of places a record might be viewed and I'll need to make sure all possibilities are covered.
3. My understanding of GDPR is that allowing complete removal of a user's record data is generally required, but that biological data is an oddity due to the archival nature of it. For example, it may not be possible to trace all the destinations that a record has been exported to (recording schemes, LRCs, NBN, GBIF, etc etc). BRC have had internal discussions and legal advice on how GDPR affects biological recording so it may be worth contacting them. As it stands, if a user did want to delete all their records, I would expect we'd accept their request, but would not be able to guarantee that all copies of the record are removed elsewhere.

**Comment by davidnicholls125** [comment]
Thanks. I'll ask Martin about the GDPR question. I think we need to leave the username as is for now, not least because we are short of funds and there are more pressing needs. I'll pass on your feedback and raise it again if we decide to make a change.
