### ISSUE TITLE
Oranise images issue

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#52]
I find that when deleting a lot of images from the Organise Images page it doesn't bring up the completion popup and just hangs. I've left it for 10-15 minutes without change. However if I refresh the page the changes have been saved. An example is Nephrotoma flavescens which I edited around 2.10pm 14th July. 
![image](https://user-images.githubusercontent.com/80914584/125629716-69e25bba-8e07-4af2-86ee-e0f49fdc39e7.png)

**Comment by davidnicholls125** [comment]
Just tried to delete 100 images or so from the Blue-tailed Damselfly page and it has just hung after 15 minutes waiting.

**Comment by johnvanbreda** [comment]
I think that due to the need to load species page data, then update data both in Drupal and Indicia, it's taking about 0.6 seconds per image. I suspect there's a 30 second timeout on the operation set on the server since it's done in one request. I suspect I could optimise this a bit but I don't think it will be dramatically better, so at some point you will hit this problem again. Keeping to less than about 40 images each time should work.

We could implement a more clever solution where the batch of images to delete are added to a queue and processed in the background, but this would be fairly complex and might introduce issues where the changes aren't immediate.

**Comment by davidnicholls125** [comment]
OK thanks. Probably best if we keep to deleting smaller batches as suggested.
