### ISSUE TITLE
TVK changes

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#54]
Concerns have been expressed about the elasticsearch downloads displaying iRecord species names instead of those used by NS. Sue Timms, one of our trustees and the manager of the VC55 records centre found that our records for Stigmella nylandriella are downloaded as Stigmella magdalenae. S. nylandriella was included on the the last TVK updater file (3 August 2020) but it still showing NBNSYS0100005606 on both Indicia and Drupal. Should this have updated?
![image](https://user-images.githubusercontent.com/80914584/129410115-75fbae20-a0ae-4f56-b925-9062fa1f863b.png)
Has there been any iRecord species inventory updates since August 2020?
This has led to the question being raised as to whether we should switch to using the iRecord species list instead of our own and it will get discussed at the next trustees meeting. How much of a job would it be to make the switch and can you think of any major cons? Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the issue here is that your TVK for S. nyandriella is wrong. You can see here that NBNSYS0100005606 is actually Stigmella magdalenae, with a synonym Stigmella nylandriella sensu auctt. nec (Tengström, 1848): https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0100005606.
Here's the correct one: https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0000504366.

The iRecord copy of UKSI was updated in April, and is soon set to switch to a mode where it updates more or less continuously as changes are applied to the NHM copy.

As per your last question, switching to the UKSI taxonomy will make things considerably less complicated as there will be less to maintain for you and there are a few areas of code which will become simpler. E.g. when iRecord App records are copied into NatureSpot we currently need to map them from UKSI to the NatureSpot list and that would no longer be necessary. Your taxonomy editing would only be for the Drupal species account and there would be no need for these changes to be reflected on the warehouse species list.

The main disadvantage of adopting UKSI is that the group names are not your preferred ones. This need not affect your species menu, since that can be done using Drupal content which you retain control of, but the Explore reports and other reports will return the UKSI group names, not NatureSpot ones. I can't see a quick and easy solution to this - I'm sure a solution exists, but it might take some effort to implement.

**Comment by davidnicholls125** [comment]
Thanks. The last update file we received was in August 2020, we didn't get one for the April update. Shouldn't this have been sent to us?
How will the NS updating work when iRecord is updating continually?
In terms of a possible move to the UKSI, the group names issue is something we could live with I think. A few other questions please:
1. Would the transition involve much work? A rough cost would help (taking into account the points below)
2. Could we limit the species list on the recording form ie. to VC55 species? (our RAG ratings and recording advice only exist where we have a species page)
3. How would we know when a 'new' species has been recorded so that we can set up a drupal species page?
4. We currently have 36 taxon entries not on the UKSI, would these be lost? (those with made-up TVKs)

**Comment by davidnicholls125** [comment]
I corrected the TVK for Stigmella nyandriella to NHMSYS0000504366 yesterday but the records are still appearing as Stigmella magdelanae. Shouldn't they update automatically?

**Comment by johnvanbreda** [comment]
I've just applied the update script to sync your list to UKSI and supplied you with the resulting file of changes.

When iRecord is updating UKSI continually, we can keep your list in sync in the background. The difficulty comes when an accepted name TVK changes so your species account page will have the wrong key. In the long term this may be fixed by switching to using organism_key as the species concept identifier as it is more stable than the accepted name TVK. In the shorter term, we might just be able to provide a report that you can regularly access to check for changes (and perhaps link an automatic email alert to this report). 

1. Tasks include:
   * Create a scratchpad list from your list (see below) and provide a tool for you to keep this up to date.
   * Create a new list for just "+ new species" and your 36 custom taxa (see below)
   * Switch recording form to UKSI+custom list with scratchpad list filter so only allowing species in VC55 to be recorded.
   * Remove code from the app->naturespot sync process which changes the species list of the record's taxa.
   * Write a script which maps all the existing data back from the VC55 list taxa to the correct version on UKSI.
   * A few changes on the site where we refer to taxon_list_id=8, which must now refer to list 15 + custom list.
   * Check process for addition of species to list 8 as no longer required.
   As a rough estimate, there is several days work here, probably 3-4.
2. I've just experimented with something called a "scratchpad list" which is a tool developed for creating lists of species for site trait analysis on brc.ac.uk/pantheon. The species search can be limited to the content of a scratchpad list and there are examples which I've just tried that have up to 8000 species on them. The performance of search was fine, which was my main concern. So, we'd be able to do this, yes.
3 & 4 - we can have a 2nd custom list included in the search results, so you would be able to include "+ new species" as well as your 36 additional entries.

**Comment by davidnicholls125** [comment]
Another TVK issue. The Indicia page for Neuroterus numismalis had the TVK entered for N. politus. It has been corrected now but can you think why it was incorrect, given the TVK update done just a few days ago?

**Comment by johnvanbreda** [comment]
@davidnicholls125 the TVK update check only detects a certain type of problem - where the VC55 list has an accepted name TVK that is the TVK of a synonym on UKSI (and therefore there is a different accepted name TVK on UKSI).

**Comment by davidnicholls125** [comment]
We've noticed that the Indicia TVKs have been updated for Puccinia distincta to BMSSYS0000015647 and Puccinia lagenophorae to NBNSYS0000021917. However our drupal species pages still had the previous invented TVKs. Should these have been updated in the recent TVK update you ran?

**Comment by johnvanbreda** [comment]
No, the problem that my script detects was where your taxon was relegated to a synonym and the preferred name had changed. I'm not sure what the circumstances for the TVK changing for these names was - it seems unusual to just change the TVK on a name.
