### ISSUE TITLE
Full screen options

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#60]
We've been wondering if it would be possible to enable a full screen view of the website? In particular the galleries would be much better with a wider format option.

**Comment by johnvanbreda** [comment]
Yes, this is possible.  Options are:
1. Make the whole site a bit wider.
2. Make certain pages on the site (e.g. gallery pages) wider, or even full width.
3. Provide an option for the user so they can toggle full-width mode on or off.

The first 2 options are easy to implement, but the 3rd option will require some coding so is more complex.

**Comment by davidnicholls125** [comment]
Can we try making the gallery pages full width as a starter?

**Comment by johnvanbreda** [comment]
That's done.

**Comment by davidnicholls125** [comment]
Thanks. Minor issue - the right hand column has stretched wider too so the images don't fit. Is it possible to retain the original  width on this column?

**Comment by johnvanbreda** [comment]
The Bootstrap template we are using is designed for fluid columns which occupy a proportion of the space available. Although I can fix this column's width, the difficulty is then making the other column occupy 100% of the remaining available space. Rather than change the template to do something it isn't designed for, how about changing the way the 2 images work so they are placed on a flexible width panel of the same colour, so they occupy the available width corrrectly? Here's a mock-up:
![sidebar](https://user-images.githubusercontent.com/2392594/131812045-6852c14f-2677-45a4-8521-c0c1361406c8.jpg)

**Comment by davidnicholls125** [comment]
That's fine, thanks. I was thinking of this as a fallback if the columns couldn't be adjusted independently.

**Comment by johnvanbreda** [comment]
Re-opening as the above was just a mockup.

**Comment by davidnicholls125** [comment]
I've used image responsive to adjust the sizes of the two images.
