### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#65]
We are working with the Wildlife Trust on their Charnwood Landscape project and have set up a project for this so their records can be tagged and filtered. A couple of questions have been asked:
1. When their volunteers use the app to record, how do they select the Charnwood project?
2. We have discussed setting up a Wild Place for the Charnwood area but they would like to be able to see just the project tagged records and images. Can we add an optional filter to the Wild Place template to select a project?

**Comment by johnvanbreda** [comment]
1. Because the records are transferred from iRecord using a "NatureSpot Leicestershire & Rutland" activity, they can't also be part of the Charnwood project. So the solution here is for me to add a new activity in iRecord "NatureSpot Leicestershire & Rutland - Charnwood" and alter the transfer code so that records posted to this activity are moved into NatureSpot and the Charnwood project. It's about 1 hour to setup - is that Ok?
2. Yes, but maybe about 2 hours work to setup. Or slightly easier would be a link to the Explore page but filtered to Charnwood project records.

**Comment by davidnicholls125** [comment]
Thanks. Go ahead with adding the NatureSpot-Charnwood project. I'll consult the Wildlife Trust on the Explore page suggestion and get back to you on this.

**Comment by davidnicholls125** [comment]
We also need an iRecord activity setting up for Loughboro' Nats. I guess we will want one for every project, can we set them up? If not please go ahead with both projects.

**Comment by davidnicholls125** [comment]
We have now set up a third project, WTWTA, and need this adding as an iRecord activity too please.

**Comment by johnvanbreda** [comment]
FYI I will try and get the projects setup tomorrow morning.

**Comment by johnvanbreda** [comment]
@davidnicholls125 if you search for NatureSpot there are now additional activities ready for you to use.

**Comment by davidnicholls125** [comment]
Thanks John.
