### ISSUE TITLE
Drupal 9 upgrade

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#68]
The board agreed this morning to go ahead with the D9 upgrade which we had provisionally agreed with you to do in November - is this still OK? There were a number of concerns due to the unforeseen consequences we experienced following the D8 upgrade. I know we discussed this with you during the zoom chat earlier in the year and you reassured us it won't be as painful but only a few of the trustees were present. Please could you respond by summarising your thoughts and expectations on the D9 upgrade to provide more reassurance? You mentioned a range of costs depending how well it all went so it would be helpful if you could include this too. Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 firstly, just to confirm that migrating from Drupal 7 to Drupal 8 was a substantial task, mainly because the internal code for Drupal 8 is based on the Symfony library, so is quite different. Therefore nearly all code that interacts with Drupal has to do so via calls to the relevant Symfony library, which will be different to the way it was done in Drupal 7. 

Migrating from Drupal 8 to Drupal 9 is quite different in scale, because Drupal 8 and Drupal 9 are effectively the same thing, with Symfony at the core. In fact the only reason why the major version number has changed is because Drupal 9 drops support for some old "deprecated" function calls, i.e. ways of doing things that have been replaced by newer, better ways of doing the same thing. However, if your code already uses the preferred way of doing things in recent Drupal 8, it will actually work without any changes in Drupal 9. This is illustrated by the fact that modules can now support both 8 & 9 with a single set of code (the Indicia module is now Drupal 8 & 9 compatible for example).

The upgrade from 8 to 9 can be summarised as:
1. Check all downloaded modules are running the latest versions and that the versions are Drupal 9 compatible.
2. Scan all custom modules (there is one for NatureSpot which does things like the image organiser) and update the code to the latest best practice which will be Drupal 9 compatible.
3. Do a normal Drupal upgrade (there is no difference at this point in going from 8.8 to 8.9, or 8.9 to 9.0).

I am relatively comfortable with updating the custom code (task 2) and there are tools to automatically search for the outdated code that needs changing, so I should be able to do this in a day. Task 3 is a normal upgrade, so should be achievable in half an hour, but I would suggest that I take a backup first and trial the upgrade before doing live, so add a few hours.

That leaves the first task. I've just scanned the modules we are using and found that we have a module "Node clone" which is outdated and will need to be uninstalled. It doesn't affect the day to day operation of the site and there is a replacement (Quick Node Clone) which should be OK. The good news is that all the other modules in use on the site are available in Drupal 9 compatible versions. 

There is a small chance that upgrading one of the modules will cause an issue, but the risk of this happening is no greater than if we were updating to just a higher Drupal 8 version. 

So, if you can confirm that the trustees are happy, or let me know if you want more explanation. Once you are happy for me to go ahead I can do most of the preparation, like upgrading the downloaded modules and changing the NatureSpot specific code, so when the actual upgrade occurs it should be straightforward. I'd expect the total to be do-able in 2 days, assuming that nothing unforeseen occurs.

**Comment by davidnicholls125** [comment]
Thanks John, this is very reassuring! I've shared it with the trustees and we are happy to go ahead. Presumably the site will be down for a while so can you let me know when this will be?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I'd like to take the site offline for an hour or so first, just to bring all the modules up to date. Is there a good time for this, or a bad time I should avoid?

**Comment by davidnicholls125** [comment]
Anytime really, but it would help to have 24 hours notice so we can put up a message.

**Comment by johnvanbreda** [comment]
If you are happy for me to do some updates at 2pm tomorrow that would suit me @davidnicholls125. Let me know if that's OK.

**Comment by davidnicholls125** [comment]
That's fine, thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the site is back online. 

I've upgraded to the latest Drupal 8 version now (not D9 yet!), and also upgraded all the modules to their latest versions so they are ready for Drupal 9, apart from the search_api module which I could not upgrade. That is because Drupal 9 requires version 10.3+ of MariaDB (the database on the server that holds the Drupal content) but the server is running 10.1. Please can you ask Clook if it is possible to upgrade the MariaDB version?

I've also prepared all the custom NatureSpot code for Drupal 9, though the version on the server is still the old code at this point, as it needs a bit of testing.

**Comment by davidnicholls125** [comment]
Thanks. I've made the request to Clook.

**Comment by davidnicholls125** [comment]
Clook are looking into it. In the meantime they have asked this question:
What are the requirements for MySQL version for the same feature? This server is due to be migrated in the near future, but the current plan is for this to be a MySQL server rather than MariaDB.

**Comment by johnvanbreda** [comment]
MySQL 5.7.8+ - see https://www.drupal.org/docs/system-requirements/database-server-requirements

**Comment by davidnicholls125** [comment]
Thanks, I've passed this on.

**Comment by davidnicholls125** [comment]
Clook response:
This not something that can be done for just one account as it's a server wide service and we need to give customers notice with regards to any server-wide changes, even though they should be minimal.
How urgent is this requirement? There is current no ETA on when we might update optweb1 in the meantime before the server migration, but we have other servers we can potentially migrate you to that have MySQL 5.7.

**Comment by davidnicholls125** [comment]
Shall we tell Clook to move us onto a new server with MySQL 5.7?
After today I will be away for a week so can you liaise with David Gould if any issues arise please.

**Comment by johnvanbreda** [comment]
@davidnicholls125 yes, assuming that the delay for the upgrade to optweb1 will be longer than the planned migration to Drupal 9's timescales, we will need them to move to a server that has MySQL 5.7. It would be worth confirming first that the proposed new server will have similar performance or better though.

**Comment by davidnicholls125** [comment]
Clook confirmed comparable performance and have now moved us to the new server.

**Comment by davidnicholls125** [comment]
Can you update us on where we are with the upgrade? Thanks.

**Comment by johnvanbreda** [comment]
I now need to re-do the upgrade for the module that failed last time, and whilst do so bring Drupal core up to date as there is a new version of this as well. Can I plan in a time to do this upgrade, Tuesday would be good for me?

**Comment by davidnicholls125** [comment]
That's fine thanks. If you can give a time when the site will be down we can advise users.

**Comment by johnvanbreda** [comment]
@davidnicholls125 if all goes to plan I will do the upgrade this afternoon.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the upgrade is done.

Please let me know if you spot any issues.

**Comment by davidnicholls125** [comment]
Great, many thanks.

**Comment by davidnicholls125** [comment]
A bit hasty of me to close this issue! The image organiser isn't working - dragged images don't stay in other other sections.

**Comment by davidnicholls125** [comment]
Please could you fix the image organiser as the next task? It is widely used and I'm receiving a number of questions about the problem! Thanks.

**Comment by johnvanbreda** [comment]
Will do - I've been tied up with the iRecord Drupal 9 migration, but I'm on this now.

**Comment by johnvanbreda** [comment]
@davidnicholls125 The Image Organiser is now fixed. It's using a new drag/drop component which doesn't need you to drag the image onto an empty box - you just drag them into place.

**Comment by davidnicholls125** [comment]
It's not working I'm afraid. It won't save the changes I made to the Abia page (8 deletions + 8 images moves) - it just hung for 5 minutes and hadn't saved any of these changes. Graham also reports that he is getting the message that there are no changes to save when he tried to make a change. Furthermore when dragging an image the screen won't scroll so you can't move an image to a position that isn't visible.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've fixed one problem in the saving. I've also improved the drag scroll - it seems a bit finickity though but as it's a third party control it's not easy for me to improve it. For example if you drag up it is faster than dragging down, so you may need to drag up then drag down again to get the precise location.

**Comment by davidnicholls125** [comment]
Thanks, that seems to work OK. Dragging up only works if you hover at a certain point and not if you swipe up completely but it works well enough. It's not often that we need to drag down anyway. Thanks.

**Comment by davidnicholls125** [comment]
Another problem, only administrators can post to the forums.....

**Comment by johnvanbreda** [comment]
All logged in users can now post to the forums. The new version of the Recaptcha module needed a library added which I've done.

**Comment by davidnicholls125** [comment]
Another issue that has occurred since the upgrade is that we have lost captions and the navigation arrows from images. The closure X is also very distant from the image and easily missed. Is it possible to reset these features? Thanks.

**Comment by johnvanbreda** [comment]
Reverting isn't possible, as we are sometimes forced to upgrade to more recent versions of libraries in order to keep everything compatible. The new version has a toolbar in the top right with additional functionality (zoom, a thumbnail gallery etc) so the layout is a little different which I can't easily change. However I've improved the appearance to make it clearer, increasing the button size and darkening the background. I've also added the captions.
