### ISSUE TITLE
Image download questions

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#72]
I've been working on the new image download (which has been very useful in identifying a few issues). The download lists records without images but the total is far short of the total number of submitted records - so which records are missing? It would be useful for all records to be included, ideally with the verification status added.
A few records on the list are a bit of a puzzle in that the species are not on either Drupal or Indicia. I know the species name is driven by the TVK so I wondered if we have that species under a different name so I've searched for the TVK but that doesn't appear to be present either. Have the species been deleted from Indicia perhaps?
Examples:
1. 336304 Myriolecis hagenii BMSSYS0000048298 (entry species = Lecanora umbrina which is a synonym)
2. 35176 Chrysotropia ciliata NHMSYS0020784913 (entered as same)
A different question - the record below has downloaded with a TVK different to that on Indicia for this species. It doesn't exist as a TVK on NBN so where do the TVKs on the download come from?
2059744 Aphis armata NHMSYS0020700000
Thanks.

**Comment by johnvanbreda** [comment]
I just tried a download and received 375K records (all records filter) - is that not about right? I've added verification status fields.

1. Lecanora umbrina has a TVK NHMSYS0020990363 which maps to Lecanora hagenii on UKSI, a synonym of Myriolecis hagenii. Your original taxon record has been deleted but the records are still extant. 
2. This is also one where the species has been deleted, but not the occurrences. It's still valid on UKSI.

When you delete a taxon, the data stays in the database, but is flagged with deleted=true. This does not delete the occurrences pointing to it, since the system might expect that the user doing the deletion would know better how to handle this than to do something automatically. So the occurences still exist and still point to the deleted taxon, so it's still possible to include the occurrence in extractions. 

Here's a query I just used for finding records linked to deleted taxa:

```sql
select o.id, o.taxa_taxon_list_id, t.taxon, t.external_key
from occurrences o
join taxa_taxon_lists ttl on ttl.id=o.taxa_taxon_list_id
join taxa t on t.id=ttl.taxon_id
where o.deleted=false and (ttl.deleted=true or t.deleted=true)
and o.website_id=8```

The file is attached (rename to *.csv to open in Excel).
[deleted-taxa-records.txt](https://github.com/johnvanbreda/naturespot-d8/files/7614184/deleted-taxa-records.txt)
