### ISSUE TITLE
Elasticsearch cache

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#76]
Symplecta pilipes (synonym of Trimica pilipes)was wrongly categorised in 'Flies' rather than 'Craneflies'. We corrected this in Indicia two weeks ago but it still shows it in the Flies taxon group. The old verification page does however display it in Craneflies so presumably this is a caching issue. I've cleared the Indicia cache but it hasn't made any difference. How often does the elasticsearch update and how do we clear this?
![image](https://user-images.githubusercontent.com/80914584/143211148-00ef2a2a-53a7-4dfe-a34a-44cf1e8d3210.png)

**Comment by johnvanbreda** [comment]
The records need to be edited and saved to refresh them - since taxonomy changes elsewhere are normally triggered by an automated script which can include the triggering of the occurrence updates required. Since your changes are manual you don't benefit from this.

A better long term solution will be to integrate the following SQL after the saving of a taxon name, so that it forces a refresh:
```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, 100, 3, now()
from cache_occurrences_functional where taxon_meaning_id=xxx;
```

I'll leave this open but lower the priority.

**Comment by davidnicholls125** [comment]
Thanks John. We do quite regularly make taxonomy changes so you proposal sounds very helpful. Please can you do this?

**Comment by johnvanbreda** [comment]
This is now done - it will create a background task that does the update for you, normally within a few hours.
