### ISSUE TITLE
Projects - admin page

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#77]
We have set up a second project: Loughboro' Nats. A test record didn't appear on the page in the hour after it was verified (though it is there now). Is there a way of manually forcing an update?
I've masqueraded as Hazel and can access the project's records page but not the project admin page - is this correct? The URLs for these project records pages is impossible to remember, can we set an alias?
Please can you add the recorder name as a default to the display? Also the images and ID column headers are missing in the download, can you add these please.

**Comment by davidnicholls125** [comment]
Please can you look at this and #65 as the next priority? Thanks.

**Comment by johnvanbreda** [comment]
I think the timing of this issue relates to the iRecord migration and I know things were queued on the server at that time. There is a queue of records to update on Elasticsearch which we can't jump, but we can requeue a record if it needs a refresh. At some point we'll probably want to look into speeding up the queue processing task generally on the warehouse, but there isn't much we can do at this point. Hopefully the length of time taken in this instance was an anomaly though. 

Do you mean the Edit page for the project details when you say "Project Admin page"? At the moment, you have to have a permission "Iform groups admin" in order to access the projects list page and the projects edit page and only administrators currently have that permission. I can give all users this permission so that the projects list page is accessible to all users and the edit page will then be accessible if they are a project admin. Or would you prefer me to create a role which you have to add to the user profiles of people who are project admins to enable access? The latter is a bit more secure, but a bit more work for you.

I tried using the Drupal aliases tool to create an alias for the explore pages, but it doesn't work with the parameters. I can write a custom route which maps from a path that contains the project name to the correct Explore path - about 2 hours work.

Recorder should already be one of the default columns. In the download, the ID column should have a title but the column before doesn't - that's a text version of the status icon. I added a title to the Images column.

**Comment by davidnicholls125** [comment]
Thanks. I think we can get round the URL alias issue by creating a simple 'project' page with the link embedded. Only project admins will be able to actually open the link. This page can then be the access route into viewing project records.
I don't think the recorder was included in the default as I added it, but it is there now anyway.
I'm having trouble setting up the explore page for the latest project - WTWTA. It just won't save the changes. I've taken a screenshot so you can see if there is an obvious reason. I've tried several times.
![image](https://user-images.githubusercontent.com/80914584/145192428-d4233980-89d3-4472-9e6e-f21662107db7.png)

**Comment by davidnicholls125** [comment]
Also please can you set up therse three projects as activities on iRecord for app use (see #65). Thanks.

**Comment by davidnicholls125** [comment]
I've tried again to add the Explore project records link to the WTWTA project but it won't save. Please can you look at this as a priority?

**Comment by johnvanbreda** [comment]
That's now fixed. The 3 projects are also set up on iRecord as explained elsewhere.

**Comment by davidnicholls125** [comment]
Thanks.
