### ISSUE TITLE
Charnwood Forest Regional Park

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#81]
As one contribution to our partnership with a new project we are setting up a Wild Place page for the area concerned - Charnwood Forest Regional Park. I've set up the page (https://www.naturespot.org.uk/Charnwood_Forest_Regional_Park) but as it is a large area there are a lot of records and presumably because of this it takes an age to load. Can anything be done to speed up loading? Caching perhaps?
Also, the default boundary map is too small and takes two 'zoom in' clicks to get it right. Can this be adjusted? Thanks.

**Comment by johnvanbreda** [comment]
I've fixed the zoom-out issue. and increased the cache timeout on the species counter. If this remains a problem we should switch the count code over to Elasticsearch, and possibly the other reports on the first tab.

**Comment by davidnicholls125** [comment]
Thanks, the map looks fine now. The page still takes a long time to load (as do some other WP pages). Is it just the species count that is slowing things down? Switching to elasticsearch sounds a good idea so let's go ahead with this.

**Comment by johnvanbreda** [comment]
@davidnicholls125 just to let you know I've been working on this - it's a little more complex than I hoped as getting the counts to exactly match is tricky due to slight differences in the way the data are stored.

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've spent a while today looking at this. One issue is that although when I originally tested this, the species count was the only significant culprit for performance issues loading a wild place or parish page, I've since found that the loading of the records grid and photos (plus possibly the species list) also cause some delay. So, I've developed code that could be expanded to include the other reports and written a replacement for the species count and records grid (so far). I've not done the images as the layout will take more work. 

In the species count, the old code counted the distinct "taxon meaning ID" values - this is a value that should group all names for the same taxon internally, so should give a count of taxa. Although I can replicate this, there are 2 possible issues, one being that higher taxa or infra-specific taxa are counted in addition to species, and also if you have taxonomy issues caused by deletion then replacing the same taxon, it could be counted twice. In the Elasticsearch code I can use the TVK of the species rank only for the count, so that both these issues are resolved. That means that, for 20 Acre Piece as an example, the count goes down from 126 sp to 123 sp, but I think the new value is actually more accurate. Is that OK?

Another issue with the records grid is that the recorder names are given as proper names (currently surname, first name format), rather than the user's login username. Is that also OK?

**Comment by davidnicholls125** [comment]
Thanks John. I've just tried loading the page and still took ages then I got an error message that the elasticsearch query had failed - but I appreciate its still a work in progress. The new species count code seems fair enough. Is this the same basis as that used for the species count on the home page? Recorder name format is OK I think. We already see full names on the Explore pages. Presumably these changes will apply to all WP pages? Can they be also used on the parish pages?

**Comment by johnvanbreda** [comment]
@davidnicholls125 at the time you tried loading the page this morning I hadn't removed the old count code, hence the time taken. I'd just added a hidden block with the new outputs so I could compare them. The error occurred because of a small issue in the site boundary polygon (a point that was repeated twice) but I've managed to run code that ensures all your site polygons don't have this problem, as Elasticsearch seems to be fussy about things like this.

I've now switched both Wild Places and Parish pages to use the new code for the species count and records grid. This definitely improves the initial load time of the page, but it's not perfect - to make further improvements we need to tackle the species list and the latest images block as well.

**Comment by davidnicholls125** [comment]
Thanks. It does load more quickly now. Can we modify the latest records list please by removing the columns for 'Identified by' and 'Automated checks'. How much work would it be to sort out the species list and latest images block?
![image](https://user-images.githubusercontent.com/80914584/148930658-b519b5fd-7b7c-4296-b0ae-9ddeea77a09a.png)

**Comment by johnvanbreda** [comment]
Ah - I think that's remembering your column settings from another page, the list of columns should be much simpler. I've hopefully disabled the remembering of your settings so can you check for me please?

The species lists tab should take an hour or two. The latest images would be similar if it's OK that the images for a record get grouped into a single thumbnail "panel", rather than being separated. See https://irecord.org.uk/butterfly-summary-2021 for an example, on the Trending tab. I.e. each bordered box contains all the images and a single set of labels per record. If you need it as it is now (each bordered box contains a single photo and set of labels, so multiple boxes per record potentially) then it will take a few hours more.

**Comment by davidnicholls125** [comment]
The simpler list is appearing now. Can we restrict the display to accepted records and also keep in the location name please? Whilst for small sites it isn't very relevant, it is useful for larger sites and certainly for parishes. The butterfly link you sent doesn't show any images..... In principle yes go ahead with the species list and images panel but I'd like to check the thumbnail panel first. It would be much preferable I think to have each image shown, is this possible?
The page is still very slow to load at first, but is much quicker when reloading. Is this a caching thing?

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've added the site name column and limited the records to accepted.

The link I gave was to a page with several tabs - if you click on Trending then the images should load.

I checked the performance of the Charnwood page just now. When loading without any cache hits the majority of the time is taken loading the images, with the species table next. If you reload the page it is cached by Indicia on your website so doesn't actually ask the warehouse for any data, so should be pretty fast. Even if we clear the caching on your website and reload, the PostgreSQL server does get asked for the same queries as before, but if the data have been loaded recently the data required for the queries will probably be in the operating system cache (i.e. in memory rather than on the disk) so will still run quite a lot faster.

**Comment by davidnicholls125** [comment]
Seen it now, thanks. Yes that looks OK I think so let's go ahead on that basis.
If I understand the caching then it will load quickly if there hasn't been any new records or images, but anything new will mean the cache refreshes which takes a long time. I loaded it last night in a zoom presentation and it took an embarrassingly long time, but it is quick to load this morning so I presume this illustrates the point. Which means we really do need the elasticsearch approach for both species lists and images.

**Comment by johnvanbreda** [comment]
@davidnicholls125 the caching is more time based - for example on the latest images block on a wild places page, it will stay in the cache for 30 minutes, after which there is a random chance of it being refreshed. The end result is the same though. I'll work on the Elastic versions of the images block first, then the species list.

**Comment by johnvanbreda** [comment]
I've done the images block for both wild places and parishes. I think the performance has improved a fair bit now, even though the species list is still running on the old style of report. I cleared all the caches just now and reloaded Charnwood - the page took 7 seconds to appear, plus another 7 before everything was fully loaded, which is not perfect but a lot better than it was considering how big the report area is for this page.

**Comment by davidnicholls125** [comment]
Thanks but I've just loaded the Charnwood page and it took 36 seconds before anything appeared, which is slower than previously. The image display doesn't seem right as shown on the screenshot below. One of the four Tenuiphantes images is out of the display area and the Watercress image is twice the width it should be I think.
![image](https://user-images.githubusercontent.com/80914584/150188778-072c241f-f8c5-4596-aeae-91ef5f08772a.png)

**Comment by johnvanbreda** [comment]
I've fixed the layout where the 4th image is outside the panel. The layout of the single Watercress image panel is correct though as we are relying on a "flexbox" algorithm in the browser to layout the images making best use of space. It is basically trying to fill the horizontal space where possible.

As to the performance, although I am certain we are sending less queries to the server so it will be an improvement, it still fundamentally has to scan a large number of records due to the size of the polygon, so until we remove the last species list query it can still be slow. It may also be slow if the server disk is busy on other processes. I'll try and sort the last block out soon.

**Comment by johnvanbreda** [comment]
I've now enabled the species list tab to use Elasticsearch. A couple of things to mention. Even though the page load is quicker, the time required to render Charnwoods' 3000+ long table in the browser is still a few seconds - this is simply the time required to output the page. I can't do anything about this...
...but, we could enable a pager now, instead of outputting the whole list?

**Comment by davidnicholls125** [comment]
Thanks John, it loaded quickly for me just now. Can you add the scientific taxon name to the species list please (it only has common name at present). Also if it is easy to add filter boxes to the headers this would be useful (eg to search for species from a particular taxon group or date period). We are also missing the download function for the species list so can this be added please. Let's leave the page option for now and see how it performs.

**Comment by davidnicholls125** [comment]
Can you add the download function please (for the species list). 
A good number of entries are not displaying any species, eg below, which looks very odd. I think these are higher taxon records. Can we display the taxon, whatever the rank?
![image](https://user-images.githubusercontent.com/80914584/150387166-7f976d4b-e19b-4098-89bf-c0b6b36f0485.png)

**Comment by johnvanbreda** [comment]
@davidnicholls125 I've added the download button plus used the taxon name, rather than just the name at the species level.

**Comment by davidnicholls125** [comment]
Thanks.
