### ISSUE TITLE
Species names and TVKs

### ISSUE THREAD

**Issue by davidnicholls125** [johnvanbreda/naturespot-d8#87]
The processing of the 2021 records has thrown up quite a number of anomalies in species names and TVKs. I know this has been a regularly raised topic and various amendmends have been made to your update script, but I'm struggling to explain to the other trustees exactly how it works and why we have these differences. Would you mind summarising what your script does and the process works so I can share it and also answer the specific questions below (if not covered by your summary)? I've copied below (in italics) the note you sent me and I added it to our admin guidance notes. If this needs updating please can you amend it? 

_If a UKSI update is applied by BRC, at the end of the process they will get a message about an additional script that needs to be run. This script does the following:

1.         Find all taxa in your list where the TVK now points to a name which has been relegated to a synonym, so is no longer the accepted name TVK.
2.         Downloads this file (they should pass it on to you - the note below explains what to do with this).
3.         Updates your species list data so the TVK changes are applied to existing data in the warehouse.

On receiving the file which was downloaded from the warehouse, save it in the dropbox as a csv (Naturespot/Species/TVK). Then go to https://www.naturespot.org.uk/update-tvks then select the file, wait a moment for it to upload, then submit it. Drupal will then chug through the changes and update the species accounts._

**Questions**
1. I don't think we have ever received the file from BRC referred to above so I don't think this is a reliable element. Could you let us know when BRC apply a UKSI update and who we should liaise with about getting this file? I think you applied the Drupal update last time?
2. When we update the TVK for a species on Indicia, do previous records for that taxon retain the original TVK or do they update? (I guess the underlying question is - what is the unique identifier that identifies a species when it is recorded?)
2. Does the elasticsearch data download looks up the iRecord or UKSI species name for the recorded TVK? If it can't find the TVK on this list, does it look up the species name on the NS list (eg where we have invented TVKs)? If so, could there be other entries with malformed TVKs? Is there a way of identifying the TVKs not found on iRecord/UKSI?

There may be other questions when we get the summary! Thanks.

**Comment by johnvanbreda** [comment]
@davidnicholls125 

The intention of the script is to detect the following scenario - it is not intended to be a fix for other issues that might occur.
If a species on UKSI called "abc" is renamed, then "abc" becomes a synonym of "def". The old TVK is no longer the accepted name's TVK so it gets a new one. If, before this change, NatureSpot has species "abc" on the list, it now needs to use the new TVK for "def", since NatureSpot only tracks the accepted name TVK, not the separate synonym TVKs unlike UKSI. So the intention of the script is to make sure that the species accounts are updated to the correct preferred name TVKs.

1. The file was sent to you in August '21 and we haven't done a full UKSI update since then. 
2. Yes, if you change a species TVK using the warehouse user interface, then the previous records are queued for an update (similar to the way I queued records in #95).
3. Yes, effectively. The exact process is that the data are exported with the TVK plus taxon name details from the NS list. Then, during the import into Elasticsearch, if the TVK can be looked up against the UKSI list, then the name details are standardised with the details from UKSI. If no lookup is available, then the original details are left in place.
